---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
- type: directory
  path: data
  label: Data
  create: all
  match: "*.json"
  new_doc_ext: json
- type: document
  path: data/forms/polsone/forms.json
  label: Polsone Forms
- type: document
  path: data/programs/asu-programs.json
  label: ASU Programs (Only Temporary, Use getJson in template instead probably)
- type: directory
  path: content/lps
  label: Landing Pages
  create: all
  match: "**/*"
  templates:
  - modular-lp
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - modular-lp
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
